### ISSUE TITLE
Concept Screening - Hull Types

### ISSUE THREAD

**Issue by igorro** [igorro/FOWT-docs#23]
Hull types: [expected day of completion and presentation FRIDAY 17/5/24]
Semi-submersible
Spar
TLP
Barge

Discuss general advantages and disadvantages of different hull types 
Comparisons on design, fabrication, installation, operations & maintenance and decommissioning.

**Comment by ash-thanga** [comment]
Me and Akshaye are focusing on Tension-Leg Platforms (TLP), especially technical characteristics, installation, , deployment and performance.

**Comment by ingridfung** [comment]
I have more or less finished the semi-submersible part. I left out the economical and environmental impacts as I thought it would be more beneficial to combine all types together in the analysis instead of doing it one by one. Currently did a bit of caternary mooring parts.

**Comment by KennethChanCM** [comment]
**Spar FOWT information researched and covered:**
Design, motion response, installation, maintenance
**to be researched:**
decommissioning

**Comment by Andylui123** [comment]
I have done all the technical characteristic of barge platform. Including all the points following the format given by Akshaye with all the references. Will be finishing environmental and economical point of view tomorrow

**Comment by patrickmcadam** [comment]
16/05/2024

Comments on Semi-submersible @ingridfung 
- Design & structure: good
- Installation & deployment: good
- Performance & reliability: good
- [ ] Economic considerations: seems thin, could add paragraph about how cost analysis is done and then a paragraph to introduce the table & it's study to highlight why it is relevant - at the minute it seems like a random addition.
- [ ] Add references into the body (rather than comments) - either now or when we compile the report.
- [ ] Refer to semi-submersible as "semi-submersible" rather than "semi-sub" in the report just to make it more formal.

**Comment by patrickmcadam** [comment]
16/05/2024
Comments on Spar @KennethChanCM 
- [ ] Design, Motion Response, Design merits: could be combined into one paragraph rather than several bullet points. Would be good to include an introductory paragraph to aide the flow of report.
- Installation: good (but seems to be another installation section later?)
- [ ] Maintenance: include paragraph introducing the figure, why it is relevant and what impact it has on the feasibility of a spar design for our site.
- [ ] Installation (again?): good, just combine the two 
- Decomission: good
- [ ] Add references into body of report (either now or when compiled).

**Comment by patrickmcadam** [comment]
16/05/2024
Comments on Barge Floating Wind Turbine @Andylui123 
- [ ] Technical characteristic: good, add reference into body of report (rather than as a comment!). Also do this for table and introduce what the table is showing in a paragraph beforehand.
- [ ] Platform design: good figures. Add a paragraph to introduce and talk about the figures you've included.
- Buoyancy and stability: good
- [ ] Anchoring system: good, again introduce the tables & figures you present in the paragraph also just to give them context.
- Installation & development: good.
- [ ] Assembly: what does the table show?
- Transportation: good
- Installation complexity: good
- Maintenance requirement: great
- [ ] Performance and reliability: what is DTU? Perhaps introduce your source with some context first. Do the same for the figures.
- [ ] Fatigue and durability 3.2 and Dynamic response 3.3 could be one section.
- [ ] Mooring system (taut): good. Ensure reference figure. Numbering of the following section appears inconsistent.

Comments on Mooring system (catenary) @katrinachengg @miladelgado 
- [ ] 1.3 Mooring system - (around pg 10) confused at this part? Is it meant to be somewhere else?
